# Generated by Django 3.2.16 on 2022-11-12 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0006_alter_blog_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='blog',
        ),
    ]
